### ISSUE TITLE
libvterm optional for neovim?

### ISSUE THREAD

**Issue by jedahan** [medvid/exheres#3]
is libvterm optional for neovim?
if possible, could you make it an option?

Since libvterm is like, scm only and I thought exherbo policy was non-tagged scm versions should be masked....

**Comment by medvid** [comment]
libvterm is not optional.
https://github.com/neovim/libvterm doesn't have any releases.
we might want to package libvterm snapshot that pulls known git commit and mask scm, but I personally have no problem pulling from git master (don't care).

**Comment by kapsh** [comment]
@medvid It feels weird to rebuild weekly package with average of five commits in year. I can add exheres which pulls snapshot, will you accept it?

**Comment by medvid** [comment]
Submitted https://github.com/jedahan/exheres/pull/3

Closing the issue, there is nothing to fix in this repo.
